[character]
success_symbol = " [>](bold green)"
error_symbol   = " [>](bold red)"
vicmd_symbol   = " [NORMAL ❯](bold green)"

[package]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[java]
disabled = true

[erlang]
disabled = true

[rust]
disabled = true
