-- local ht = require('haskell-tools')
-- local buffer = vim.api.nvim_get_current_buf()
-- local def_opts = { noremap = true, silent = true, }
-- ht.setup {
--     hls = {
--         on_attach = function(client, bufnr)
--             local opts = vim.tbl_extend('keep', def_opts, { buffer = bufnr, })
--             -- haskell-language-server relies heavily on codeLenses,
--             -- so auto-refresh (see advanced configuration) is enabled by default
--             vim.keymap.set('n', '<space>hs', ht.hoogle.hoogle_signature, opts)
--             vim.keymap.set('n', '<space>ea', ht.lsp.buf_eval_all, opts)

--             vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action, opts)
--             vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
--             vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
--             vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
--             vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
--             vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
--             vim.keymap.set('n', '<C-k>', vim.diagnostic.goto_prev, opts)
--             vim.keymap.set('n', '<C-j>', vim.diagnostic.goto_next, opts)
--             vim.keymap.set('n', '<leader>cr', vim.lsp.buf.rename, opts)
--             vim.keymap.set('i', '<C-l>', vim.lsp.buf.signature_help, opts)
--             vim.keymap.set('n', '<space>cf', function() vim.lsp.buf.format { async = true } end, bufopts)

--             vim.keymap.set('n', '<space>d', vim.diagnostic.open_float, opts)

--             if vim.api.nvim_buf_get_option(0, 'filetype') == 'haskell' then
--                 vim.api.nvim_command[[
--                 autocmd BufWritePre <buffer> lua vim.lsp.buf.format()]]
--             end
--         end,

--         default_settings = {
--             haskell = {
--                 hlintOn = true,
--                 formattingProvider = "fourmolu"
--             }
--         }
--     },
--     repl = {
--         handler = 'builtin',
--         builtin = {
--             create_repl_window = function(view)
--                 -- create_repl_split | create_repl_vsplit | create_repl_tabnew | create_repl_cur_win
--                 return view.create_repl_split { size = vim.o.lines / 3 }
--             end
--         },
--     }
-- }

-- -- Suggested keymaps that do not depend on haskell-language-server:
-- local bufnr = vim.api.nvim_get_current_buf()
-- -- set buffer = bufnr in ftplugin/haskell.lua
-- local opts = { noremap = true, silent = true, buffer = bufnr }

-- -- Toggle a GHCi repl for the current package
-- vim.keymap.set('n', '<leader>rr', ht.repl.toggle, opts)
-- -- Toggle a GHCi repl for the current buffer
-- vim.keymap.set('n', '<leader>rf', function()
--   ht.repl.toggle(vim.api.nvim_buf_get_name(0))
-- end, def_opts)
-- vim.keymap.set('n', '<leader>rq', ht.repl.quit, opts)
